// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5pojZmRONvuERPHRU-ofnKU6C6wHmLpU',
    appId: '1:813226001642:web:4e51d9a857ab3b81348393',
    messagingSenderId: '813226001642',
    projectId: 'flutter-abdallah-banan-model',
    authDomain: 'flutter-abdallah-banan-model.firebaseapp.com',
    storageBucket: 'flutter-abdallah-banan-model.firebasestorage.app',
    measurementId: 'G-WCBT633M9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmEB8iYScBSx7ZeqVOZZOk11GQt6L488U',
    appId: '1:813226001642:android:44a0198b4657a29a348393',
    messagingSenderId: '813226001642',
    projectId: 'flutter-abdallah-banan-model',
    storageBucket: 'flutter-abdallah-banan-model.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxXo62TvGf0iY8EqtfkdbUfcECHMKvgA',
    appId: '1:813226001642:ios:1f44b6b8c927fc21348393',
    messagingSenderId: '813226001642',
    projectId: 'flutter-abdallah-banan-model',
    storageBucket: 'flutter-abdallah-banan-model.firebasestorage.app',
    iosBundleId: 'com.example.multimodalAiPrototype',
  );

}