// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2VpF6T3-ToDMj_2XJlTQh6sAGnNuPVks',
    appId: '1:959782953795:web:8f736f0976a84ba2d045f6',
    messagingSenderId: '959782953795',
    projectId: 'abdallah-mc-hackweek',
    authDomain: 'abdallah-mc-hackweek.firebaseapp.com',
    storageBucket: 'abdallah-mc-hackweek.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpPfAHxUfVDzFr-3Kw148afZTzuxf4EI',
    appId: '1:959782953795:android:2393f3784a838fccd045f6',
    messagingSenderId: '959782953795',
    projectId: 'abdallah-mc-hackweek',
    storageBucket: 'abdallah-mc-hackweek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsOjYS5xvIcbE3bilCn606heMe-U44fI',
    appId: '1:959782953795:ios:96896541abe4aadfd045f6',
    messagingSenderId: '959782953795',
    projectId: 'abdallah-mc-hackweek',
    storageBucket: 'abdallah-mc-hackweek.firebasestorage.app',
    iosBundleId: 'com.example.multimodalAiPrototype',
  );

}